### ISSUE TITLE
Update README / add warnings for non-existent model name.

### ISSUE THREAD

**Issue by maxim-h** [eonurk/ceLLama#1]
Hello! Thank you for this project.

When trying to follow the instructions in the README I got unexpected behaviour where all responses were just `NULL`.

After some googling I figured out the README suggests to pull llama3.1, while the default value for the model parameter in the `ceLLama` function is llama3. This leads to a 404 response from ollama and an empty result in ceLLama. Specifying `model = "llama3.1"`  explicitly solves the issue.

Could you update the README to mention that the model name mismatch might lead to empty results or ideally add some warning message in case of  a 404 response instead of just returning `NULL`?

**Comment by eonurk** [comment]
You're right, I have fixed the issue for now, but I need to think about a better way to ensure consistency. Thank you.
